// Types and constants for the hymnal. The hymn data itself lives in
// /public/data/{lang}.json, generated by data-pipeline/ and fetched lazily —
// see hymnal.tsx for loading and cross-language resolution.
//
// Rights model: every entry carries how we may show its text.
//   'pd'         — text verified public domain (pre-1931 / KJV scripture)
//   'restricted' — under copyright; we show metadata only until licensed
//   'licensed'   — cleared by the Pacific Press / Review & Herald agreement
//
// Cross-language model: each hymnal edition (English SDAH, Yorùbá Ìwé Orin
// Mímọ́, Igbo Abụ Ọtụtọ, Hausa…) numbers its hymns differently. English
// songIds are "sdah-<number>"; other editions use "<lang>-<number>" plus an
// optional sdahRef pointing at the English number. Switching language follows
// that mapping, never the local number.

export type Verse = {
  lines: string[]
  isRefrain?: boolean
}

export type LangCode = 'en' | 'yo' | 'ig' | 'ha'

export type Rights = 'pd' | 'restricted' | 'licensed'

export const LANGS: {
  code: LangCode
  label: string
  hymnalTitle: string
  available: boolean
}[] = [
  { code: 'en', label: 'English', hymnalTitle: 'Seventh-day Adventist Hymnal', available: true },
  { code: 'yo', label: 'Yorùbá', hymnalTitle: 'Ìwé Orin Mímọ́', available: true },
  { code: 'ig', label: 'Igbo', hymnalTitle: 'Abụ Ọtụtọ', available: false },
  { code: 'ha', label: 'Hausa', hymnalTitle: 'Hausa Hymnal', available: false },
]

export type Hymn = {
  number: number
  lang: LangCode
  songId: string
  title: string
  category: string
  kind: 'hymn' | 'reading'
  verses: Verse[]
  author?: string
  year?: number
  rights?: Rights
  /** English SDAH number this song corresponds to, for non-English editions. */
  sdahRef?: number
}

/** Shape of /public/data/{lang}.json */
export type EditionFile = {
  lang: LangCode
  hymnalTitle: string
  hymns: Omit<Hymn, 'lang'>[]
}

export const CATEGORIES = [
  'Worship',
  'Trinity',
  'God the Father',
  'Jesus Christ',
  'Holy Spirit',
  'Holy Scriptures',
  'Gospel',
  'Christian Church',
  'Doctrines',
  'Early Advent',
  'Christian Life',
  'Christian Home',
  'Special Occasions',
  'Aids to Worship',
  'Scripture Readings',
] as const

/** True when we may render the full text of this entry. */
export const canShowText = (h: Hymn) =>
  h.rights !== 'restricted' && h.verses.length > 0
